trigger:
- test_demo

variables:
  TriggeringUser: $[ coalesce(variables['Build.RequestedFor'], 'Unknown') ]

jobs:
- job: Self_Hosted_Environment
  pool:
    name: VMpool
  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
    displayName: 'Use Python 3.9'

  - script: |
      echo "Pipeline triggered by: $(TriggeringUser)"
    displayName: 'Print Triggering User'


  - script: |
      python -m pip install --upgrade pip
      pip install selenium
      pip install -r requirements.txt
      pip install pandas
      pip install --upgrade webdriver_manager
      pip install --upgrade urllib3
    displayName: 'Install dependencies'

  - script: |
      pip install pytest pytest-azurepipelines pytest-html
    displayName: 'Install pytest and plugins'

  - script: |
      cd $(Build.SourcesDirectory)/tests
      pytest -v -s -vv -p no:warnings --html=reports\report.html --self-contained-html --capture=tee-sys
    displayName: 'Run tests'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: tests/screenshots/
      artifact: 'screenshots'
    displayName: 'Publish screenshots'
    condition: always()

  - task: PublishPipelineArtifact@2
    inputs:
      targetPath: tests/executionlogs/
      artifact: 'Executionlogs'
    displayName: 'Publish executionlogs'
    condition: always()

  - task: PublishPipelineArtifact@3
    inputs:
      targetPath: 'tests/reports'
      artifact: 'html-test-report'
    displayName: 'Publish HTML report'
    condition: always()
