# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- test_demo

variables:
  absolute_file_path_file: 'tests/resources/Envelope1.docx'

jobs:
- job: Windows_Environment
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:
      Python39:
        python.version: '3.9'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - checkout: self

  - script: |
      python -m pip install --upgrade pip
      pip install selenium
      pip install -r requirements.txt
      pip install --upgrade webdriver_manager
      # Download Google Chrome installer
      powershell -Command "(New-Object System.Net.WebClient).DownloadFile('https://dl.google.com/chrome/install/GoogleChromeStandaloneEnterprise.msi', 'GoogleChromeStandaloneEnterprise.msi')"
      # Install Google Chrome silently
      msiexec /i GoogleChromeStandaloneEnterprise.msi /quiet /norestart
    displayName: 'Install dependencies'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/copied_repo'
    displayName: 'Copy test files'


  - script: |
      pip install pytest pytest-azurepipelines
      cd D:\\a\\1\\s\\test
      pytest -v -s -vv
    displayName: 'Run tests'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/copied_repo/tests/screenshots/'
      artifact: 'screenshots'
    displayName: 'Publish screenshots artifact'
