# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- test_demo

jobs:
- job: Self_Hosted_Environment
  pool:
    name: VMpool
  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
    displayName: 'Use Python 3.9'


  - script: |
      python -m pip install --upgrade pip
      pip install selenium
      pip install -r requirements.txt
      pip install pandas
      pip install --upgrade webdriver_manager
      REM Download Google Chrome installer
      powershell -Command "(New-Object System.Net.WebClient).DownloadFile('https://dl.google.com/chrome/install/GoogleChromeStandaloneEnterprise.msi', 'GoogleChromeStandaloneEnterprise.msi')"
      REM Install Google Chrome silently
      msiexec /i GoogleChromeStandaloneEnterprise.msi /quiet /norestart
    displayName: 'Install dependencies'


  - script: |
      pip install pytest pytest-azurepipelines
      cd $(Build.SourcesDirectory)\tests
      pytest -v -s -vv
    displayName: 'Run tests'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'tests/screenshots/'
      artifact: 'screenshotssss'