trigger:
- Release_v1.0_Docusign

variables:
  TriggeringUser: $[ coalesce(variables['Build.RequestedFor'], 'Unknown') ]

jobs:
- job: DocuSign_Automation_Test_Suite
  pool:
    name: VMpool
  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
    displayName: 'Use Python 3.9'

  - script: |
      echo "Pipeline triggered by: $(TriggeringUser)"
    displayName: 'Print Triggering User'


  - script: |
      python -m pip install --upgrade pip
      pip install selenium
      pip install -r requirements.txt
      pip install --upgrade webdriver_manager
      pip install --upgrade urllib3
    displayName: 'Install dependencies'

  - script: |
      pip install pytest pytest-azurepipelines pytest-html
    displayName: 'Install pytest and plugins'

  - script: |
      cd $(Build.SourcesDirectory)/tests
      pytest -v -s test_change_sign_tag_size.py -vv -p no:warnings --html=reports\report.html --self-contained-html --capture=tee-sys
    displayName: 'Run tests'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: tests/screenshots/
      artifact: '1.screenshots'
    displayName: 'Publish screenshots artifact'
    condition: always()

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: tests/executionlogs/
      artifact: '3.executionlogs'
    displayName: 'Publish Executionlogs artifact'
    condition: always()
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'tests/reports'
      artifact: '2.html-test-report'
    displayName: 'Publish HTML report artifact'
    condition: always()
