trigger:
  - test_demo

jobs:
  - job: Windows_Environment
    pool:
      vmImage: 'windows-latest'

    steps:
      - checkout: none

      - script: |
          mkdir docuSign
          cd docuSign
          git init
          git remote add origin https://github.com/PharmaTek-solutions/DocuSign-Automation.git
          git fetch --depth=1 origin test_demo
          git checkout test_demo

          cd docuSign
          dir
        displayName: 'Clone repository, checkout branch, and list files'
