trigger:
- test_demo

variables:
  TriggeringUser: $[ coalesce(variables['Build.RequestedFor'], 'Unknown') ]

jobs:
- job: Self_Hosted_Environment
  pool:
    name: VMpool
  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
    displayName: 'Use Python 3.9'

  - script: |
      echo "Pipeline triggered by: $(TriggeringUser)"
    displayName: 'Print Triggering User'

  - script: |
      if [ "$(Build.Reason)" == "IndividualCI" ]; then
        TRIGGERING_USER=$(git log -1 --format='%an')
      else
        TRIGGERING_USER=$(Build.RequestedFor)
      fi
      echo "##vso[task.setvariable variable=TRIGGERING_USER;isOutput=true]$TRIGGERING_USER"
    displayName: 'Set Triggering User'

  - script: |
      python -m pip install --upgrade pip
      pip install selenium
      pip install -r requirements.txt
      pip install pandas
      pip install --upgrade webdriver_manager
      pip install --upgrade urllib3
    displayName: 'Install dependencies'

  - script: |
      pip install pytest pytest-azurepipelines pytest-html
    displayName: 'Install pytest and plugins'

  - script: |
      cd $(Build.SourcesDirectory)/tests
      pytest -v -s -vv --html=reports\report.html --self-contained-html --capture=tee-sys
    displayName: 'Run tests with capturing screenshots on failure'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: tests/screenshots/
      artifact: 'screenshots'
    displayName: 'Publish screenshots artifact'
    condition: always()

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'tests/reports'
      artifact: 'html-test-report'
    displayName: 'Publish HTML report artifact'
    condition: always()
