trigger:
  - test_demo

variables:
  absolute_file_path_file: 'tests/resources/Envelope1.docx'

jobs:
  - job: Windows_Environment
    pool:
      vmImage: 'windows-latest'
    strategy:
      matrix:
        Python39:
          python.version: '3.9'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
        displayName: 'Use Python $(python.version)'

      - checkout: self

  - job: list_files_job
    displayName: "List Files"
    steps:
      - script: |
          cd $(System.DefaultWorkingDirectory)
          ls -la