version: 0.2

phases:
  install:
    commands:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt  # Install dependencies
  build:
    commands:
      - pytest -v -s  # Run tests

artifacts:
  files:
    - '**/*'  # Include all files for deployment (e.g., test results, logs)
