version: 0.2

phases:
  install:
    commands:
      - echo "Installing Python 3.9 and dependencies"
      - curl -sS https://bootstrap.pypa.io/get-pip.py | python3
      - python3 -m pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install selenium
      - pip install pytest pytest-html
      - pip install --upgrade webdriver_manager
      - echo "Dependencies installed successfully"

  build:
    commands:
      - echo "Starting tests"
      - cd tests
      - pytest -v -s --html=reports/report.html --self-contained-html --capture=tee-sys
      - echo "Tests completed"

artifacts:
  files:
    - '**/*'  # Include all files for deployment
    - tests/reports/report.html  # Test reports
    - tests/screenshots/**/*  # Screenshots
    - tests/executionlogs/**/*  # Logs

cache:
  paths:
    - '/root/.cache/pip/**/*'  # Cache Python packages for faster builds


#
#This file ensures:
#
#Dependencies are installed.
#Tests are executed.
#Artifacts (like reports, logs) are created.
